# PyTorch Programming - Demonstrating Tensors
---

## Author : Amir Atapour-Abarghouei, amir.atapour-abarghouei@durham.ac.uk

This notebook will provide a few examples that show the capabilities of tensors in PyTorch Programming.

Let's start by importing what we need:

In [4]:
import torch

In [5]:

if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    x = torch.ones(1, device=mps_device)
    print (x)
else:
    print ("MPS device not found.")

print(torch.cuda.is_available())

MPS device not found.
True


One of the most interesting things about PyTorch is that tensors are designed to behave similarly to NumPy arrays. Let's start by creating a simple rank 1 tensor:

In [6]:
x = torch.zeros(10)
print('done!')

done!


and then we can inspect the tensor we have created:

In [7]:
print(x)
print(x.size())

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
torch.Size([10])


PyTorch tensors support many of the operations you would expect from a NumPy array:

In [8]:
print(x+2)

tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])


In [9]:
print(x+3 * torch.eye(10))

tensor([[3., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 3., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 3., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 3., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 3., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 3., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 3., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 3., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 3., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 3.]])


You see that we can achieve interesting results using broadcasting. Let's create a rank 2 tensor (matrix) sampled from a Normal distribution:

In [10]:
x = torch.randn(10,5)
# 10 rows, 5 columns
# torch.randn returns a tensor drawn from standard normal (mean of 0, variance of 1 - Gaussian)
print(x)
print(x.shape)

tensor([[ 0.4332,  0.4172,  1.8120,  1.1477,  0.3162],
        [-0.0973, -0.3987, -1.1430,  0.9041, -0.6732],
        [-0.7173, -1.7203, -1.1564,  0.6697, -0.0180],
        [ 0.0486,  0.0685,  1.2278,  0.0640,  0.1076],
        [ 0.5564,  1.2816,  0.3409,  0.1035, -1.0607],
        [-0.5228,  0.4165, -0.5187, -0.3530,  0.1691],
        [-0.9094, -0.4847, -0.1307, -0.3696,  0.4560],
        [-0.3245,  0.4865,  1.1111,  0.2959,  0.4888],
        [ 0.6106, -0.8410,  0.7146, -1.8369, -0.1662],
        [ 0.3937, -1.5096,  0.4678,  0.6260,  0.3683]])
torch.Size([10, 5])


We can also look at a matrix drawn from the uniform distribution:

In [11]:
x = torch.rand(10,5)
# torch.randn returns a tensor drawn the uniform distribution in the interval [0,1)
print(x)
print(x.shape)

tensor([[5.7014e-01, 5.5714e-01, 1.4820e-01, 2.1722e-01, 6.3511e-01],
        [7.3980e-01, 8.0101e-01, 9.3974e-02, 9.7667e-01, 9.7257e-04],
        [5.4966e-01, 1.4073e-01, 1.5521e-02, 1.1675e-01, 9.9222e-01],
        [4.7728e-01, 3.1515e-01, 8.0625e-01, 1.1281e-03, 1.8020e-01],
        [6.2096e-01, 6.8079e-02, 6.4618e-01, 9.3419e-01, 1.6763e-01],
        [1.5658e-01, 5.2189e-01, 9.7021e-01, 7.3499e-01, 1.4082e-01],
        [5.0191e-01, 8.9621e-02, 9.7044e-01, 3.4743e-01, 3.7675e-01],
        [1.9279e-01, 2.1548e-01, 4.6171e-01, 1.0340e-02, 2.3752e-01],
        [1.4427e-01, 6.3096e-01, 6.6305e-01, 6.7402e-01, 2.8560e-01],
        [5.1170e-01, 7.1846e-01, 1.0115e-01, 9.8704e-01, 8.2312e-01]])
torch.Size([10, 5])


We can add or remove singleton dimensions to tensors using `unsqueeze` and `squeeze`.

This adds an empty dimension to the matrix

Let's start by adding dimensions to the tensor we created earlier:

In [12]:
print(x.unsqueeze(0).shape)
print(x.unsqueeze(1).shape)
print(x.unsqueeze(2).shape)

torch.Size([1, 10, 5])
torch.Size([10, 1, 5])
torch.Size([10, 5, 1])


Note that these operations are not in-place so we haven't actually modified the `x` tensor:

In [13]:
print(x.shape)

torch.Size([10, 5])


However, PyTorch does actually support in-place operations. For many operations, by adding underscore, we can get the in-place version of the command - for instance:

In [14]:
x.unsqueeze_(1)
print(x.shape)

torch.Size([10, 1, 5])


This, of course, could have been done through assignment as well:

In [15]:
x = x.unsqueeze(3)
print(x.shape)

torch.Size([10, 1, 5, 1])


Note that we can remove dimensions using the `squeeze` operator:

In [16]:
print(x.squeeze(3).shape)

torch.Size([10, 1, 5])


Now that we have added singleton dimensions to the tensor, we can use `repeat` to repeat along the dimensions we have added:

It repeats across the singleton dimensions

In [17]:
x = x.repeat(1, 3, 1, 6)
print(x.shape)

torch.Size([10, 3, 5, 6])


PyTorch also supports indexing the same way NumPy does, which is very useful.

For instance, let's look at the size of the output when we index into the zeroth dimension:

In [18]:
print(x[0].shape)

torch.Size([3, 5, 6])


We can use the colon operator, `:`, to select data along specific spatial dimensions:

In [19]:
print(x[:,0].shape)

torch.Size([10, 5, 6])


We can also select elements up to a point using the colon operator:

In [20]:
print(x[:3].shape)

torch.Size([3, 3, 5, 6])


or we can do it the other way around where we pick everything after a given index:

In [21]:
print(x[3:].shape)

torch.Size([7, 3, 5, 6])


We can always "`view`" the elements of our tensor in different ways. Let's look at the size of our tensor again and see how many elements it has got:

In [22]:
print(f'shape of the tensor: {x.shape}')
num_elements = torch.numel(x)
print(f'number of elements in the tensor: {num_elements}')

shape of the tensor: torch.Size([10, 3, 5, 6])
number of elements in the tensor: 900


Now we can try to change our view of the tensor:

In [23]:
x.view(num_elements).shape

torch.Size([900])

We can also do this in a different way:

In [24]:
x.view(-1).size()

torch.Size([900])

We can actually view the tensor in a number of ways, as long as the number of elements remains the same:

In [25]:
x.view([10,90]).shape


torch.Size([10, 90])

In [26]:
print(x.view(x.size(2), -1).shape)

torch.Size([5, 180])


Let's take a look at tensor types in PyTorch.

By default, tensors are of type float and on the CPU

In [27]:
x.dtype

torch.float32

We can easily cast tensors to other types - for instance 64-bit integer, `long`: 

In [28]:
x = (x*10).long()
# let us look at a piece of this as it might be too big to view the whole thing:
print(x[0]) 

tensor([[[5, 5, 5, 5, 5, 5],
         [5, 5, 5, 5, 5, 5],
         [1, 1, 1, 1, 1, 1],
         [2, 2, 2, 2, 2, 2],
         [6, 6, 6, 6, 6, 6]],

        [[5, 5, 5, 5, 5, 5],
         [5, 5, 5, 5, 5, 5],
         [1, 1, 1, 1, 1, 1],
         [2, 2, 2, 2, 2, 2],
         [6, 6, 6, 6, 6, 6]],

        [[5, 5, 5, 5, 5, 5],
         [5, 5, 5, 5, 5, 5],
         [1, 1, 1, 1, 1, 1],
         [2, 2, 2, 2, 2, 2],
         [6, 6, 6, 6, 6, 6]]])


Let's confirm what "device" the tensor is on:

In [29]:
x.device

device(type='cpu')

The interesting thing is that can transfer the tensor and any subsequent operations to the GPU very easily.

Let's recreate our tensor first:



In [30]:
x = torch.zeros(10)
print('done!')

done!


In [31]:
x = x.cuda()

In [32]:
(x+2).device

device(type='cuda', index=0)

GPU operations are of course much faster and are basically the engine that run deep learning.

At certain points, you might need to use CPU again, which can be done very easily:

In [33]:
x.cpu().device

device(type='cpu')

As you see, PyTorch offers the versatility of numpy arrays but the ability to use the GPU easily.

------------
Copyright (c) 2023 Amir Atapour-Abarghouei, UK.

based on https://github.com/cwkx/ml-materials

License : LGPL - http://www.gnu.org/licenses/lgpl.html